### ISSUE TITLE
Problem with TCPPortCheck

### ISSUE THREAD

**Issue by md-toro** [newrelic/quickstarts-synthetics-library#37]
testing this script in New Relic doesn't populate response time, connection times and other graphs.  Console log messages show a response time in the millilseconds but the graphs in scripted api do not populate.

**Comment by bpeckNR** [comment]
Using these custom scripts will not populate the default UI with timing details. This is expected behavior. 

The $har object can be used to provide timing details that will populate the UI, but this is not part of the example for these snippets: 
https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/custom-timing-details/
